### ISSUE TITLE
PC与移动端适配

### ISSUE THREAD

**Issue by chanchancl** [3plus10i/UTXeolb#2]
移动端和PC端的输入应该能被自动识别。在CommentSet中增加识别来源的方法。
由于目前软件打包为win应用程序，所以目前采用的移动端文本输入方式需要用户自行进行跨设备数据传输，比较麻烦所以考虑增加输入解析方法，允许解析从网页端（adnmb.com）复制而来的文本。
用户将文本从网页端复制到软件的输入框中。用户可能会分多次粘贴。需要实现从这文本中识别出格式化的ids和nos两个list的方法。

**Comment by chanchancl** [comment]
# Solutions
- PC
python with GUI
- Mobile
    - static html page
    - wechat miniprogram

Wechat miniprogram is more convenient.

**Comment by 3plus10i** [comment]
原始预定的需求（增加PC网页端适配）已经完成。后续移动端开发预计使用静态网页，另开issue。
